name: Mirror Sync

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: 

jobs:
  mirror:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch Upstream
        run: |
          git remote add upstream https://github.com/kamranahmedse/developer-roadmap.git
          git fetch upstream --prune

      - name: Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin refs/remotes/upstream/*:refs/heads/* --force
